import type { Metadata } from 'next';
import { mont } from '@/app/fonts';
import Header from '@/components/Header/Header';
import StoreProvider from './StoreProvider';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Stackline',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={mont.variable}>
        <StoreProvider>
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
